In [4]:
my_list=[1,2,3]

In [5]:
my_list

[1, 2, 3]

In [8]:
import numpy as np

In [9]:
np.array(my_list)

array([1, 2, 3])

In [15]:
my_list2=[[1,2,3],[23,45,78],[33,11,44]]

In [16]:
np.array(my_list2)

array([[ 1,  2,  3],
       [23, 45, 78],
       [33, 11, 44]])

In [17]:
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

# np.arange(0,10)

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(4)

array([0.18015081, 0.19631843, 0.9559658 , 0.13326688])

In [23]:
np.random.rand(4,5)

array([[0.62201687, 0.60479537, 0.56036569, 0.94537693, 0.2726678 ],
       [0.6410253 , 0.8432927 , 0.27844376, 0.8479733 , 0.66483215],
       [0.31548031, 0.98601905, 0.27317783, 0.77231058, 0.1695268 ],
       [0.22395654, 0.9945347 , 0.5579695 , 0.49994554, 0.24527133]])

In [24]:
np.random.randn(5,6)

array([[-0.53956458,  1.04219701, -0.58093955,  0.39414311, -0.49162935,
        -0.78805866],
       [-0.37834318,  1.38542391, -0.21610003,  0.38038831, -0.14632509,
        -1.18097508],
       [-1.86871429, -0.48140644, -1.02434172,  0.58333653,  0.86381571,
         0.51958275],
       [ 0.39957398,  0.2057169 ,  0.96655363, -1.11502263,  1.34624422,
         0.38173811],
       [ 0.89323294,  0.30005749,  0.41746906,  0.73669711, -0.30380217,
        -0.28525198]])

In [31]:
np.random.randint(0,50)

46

In [32]:
np.random.randint(2,956)

543

In [33]:
np.random.randint(2,956,7)

array([794, 115,  10, 285, 166, 578, 260])

In [35]:
narray=np.random.randint(2,956,10)

In [36]:
narray

array([  2,  33, 876, 725, 825, 105, 432, 214, 219, 523])

In [37]:
narray1=np.arange(0,50)

In [38]:
narray1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
narray1.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
narray1.max()

49

In [41]:
narray1.min()

0

In [42]:
narray1.argmax()

49

In [43]:
array=np.arange(25)

In [44]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
array.max()

24

In [46]:
array.min()

0

In [47]:
array.argmax()

24

In [48]:
array.dtype

dtype('int32')